Fix gcc compilation of std_core_Arrays.cpp
When gcc (at least gcc 11.4.0) is used to build the project the
following error occurs:

static_core/plugins/ets/runtime/intrinsics/std_core_Arrays.cpp:256:99: error: declaration of ‘dst’ shadows a previous local [-Werror=shadow]
  256 |         auto putSafepoint = [&usePreBarrier, barrierSet, srcArray, dstArray, thread](T *&src, T *&dst, size_t start,
      |                                                                                               ~~~~^~~
static_core/plugins/ets/runtime/intrinsics/std_core_Arrays.cpp:243:11: note: shadowed declaration is here
  243 |     auto *dst = dstArray.GetStartPtr();
      |           ^~~

The `dst` and `src` arguments of the `putSafepoint` lambdas shadows the
corresponding arguments of the containing `copyWithBarriers` function.

Issue:
https://gitcode.com/openharmony/arkcompiler_runtime_core/issues/7390

Signed-off-by: Howard Roark <howard.roark1@huawei-partners.com>